nesplash/main/routes.py
from flask import Blueprint, request, current_app, render_template, jsonify, session, abort
from nesplash.models import Photo, User, Collection
from nesplash.ma import photoSchema, collectionSchema, userSchema
from nesplash.decorator import login_required


main_bp = Blueprint("main", __name__)



@main_bp.route("/")
def index():
    return render_template("main.html")

@main_bp.route("/api/photos")
def photos():
    page = request.args.get("page", None)
    arr = []
    query = Photo.query.order_by(Photo.id.desc()).offset(int(page)*12).limit(12)
    results = photoSchema.dump(query)

    for result in results:
        photo = Photo.query.get_or_404(result["id"])
        data = {
            "id": result["id"],
            "imageurl": result["imageurl"],
            "description": result["description"],
            "download": result["download"],
            "label": result["label"],
            "User": {
                "user": photo.author.username,
                "link": photo.author.link,
                "profile_image": photo.author.profile_image,
                "user_id": photo.author.id
            }
        }
        arr.append(data)
    if results != []:
        if len(results) < 12:
            return jsonify({"nextPage": None, "message": arr})
        else:
            query_data_check = Photo.query.order_by(Photo.id.desc()).offset(int(page)*12).limit(12)
            results_check = photoSchema.dump(query_data_check)
            if results_check != []:
                return jsonify({"nextPage": int(page) + 1, "message": arr})
            else:
                return jsonify({"nextPage": None, "message": arr})
    else:
        return jsonify({"nextPage": None, "message": []})


@main_bp.route("/api/photos/search")
def search_photos():
    arr = []
    keyword = request.args.get("q", None)
    page = request.args.get("page", None)
    photos = Photo.query.whooshee_search(keyword).order_by(Photo.timestamp.desc()).offset(int(page)*12).limit(12)
    results = photoSchema.dump(photos)
    for result in results:
        photo = Photo.query.get(result["id"])
        data = {
            "id": result["id"],
            "imageurl": result["imageurl"],
            "description": result["description"],
            "download": result["download"],
            "label": result["label"],
            "User": {
                "user": photo.author.username,
                "link": photo.author.link,
                "profile_image": photo.author.profile_image,
                "user_id": photo.author.id
            }
        }
        arr.append(data)
    if len(results) < 12:
        return jsonify({"nextPage": None, "message": arr})
    else:
        photos_check = Photo.query.whooshee_search(keyword).order_by(Photo.timestamp.desc()).offset((int(page)+1)*12).limit(12)
        check_data = photoSchema.dump(photos_check)
        if check_data != []:
            return jsonify({"nextPage": int(page) + 1, "message": arr})
        else:
            return jsonify({"nextPage": None, "message": arr})


@main_bp.route("/api/users/search")
def search_user():
    arr = []
    page = request.args.get("page", None)
    keyword = request.args.get("q", None)
    users = User.query.whooshee_search(keyword).offset(int(page)*12).limit(12)
    results = userSchema.dump(users)
    for result in results:
        data = {
            "User": {
                "user": result["username"],
                "profile_image": result["profile_image"],
                "user_id": result["id"]
            }
        }
        arr.append(data)

    if results != []:
        if len(results) < 12:
            return jsonify({"nextPage": None, "message": arr})
        else:
            users_check = User.query.whooshee_search(keyword).offset((int(page)+1)*12).limit(12)
            results_check = userSchema.dump(users_check)
            if results_check != []:
                return jsonify({"nextPage": int(page) + 1, "message": arr})
            else:
                return jsonify({"nextPage": None, "message": arr})
    else:
        return jsonify({"message": []})



@main_bp.route("/api/collected_photo_id")
def collected_photo_id():
    arr = []
    sess = session.get("email")
    if sess:
        user = User.query.filter_by(email=sess).first()
        collects = Collection.query.with_parent(user).order_by(Collection.collected_id.asc()).all()
        results = collectionSchema.dump(collects)
        for result in results:
            arr.append(result["collected_id"])
        return jsonify({"message": arr})
    return jsonify({"message": []})

nesplash/user/routes.py
from flask import Blueprint, render_template, session, request, jsonify, redirect, url_for, abort
from nesplash.models import User, Photo, Collection, Follow, Category, Method
from nesplash.extensions import db
from nesplash.decorator import login_required
from nesplash.user.util import send_register_mail, send_change_password_mail, s3_profile_pics, s3_public_pics
from nesplash.ma import userSchema, photoSchema, collectionSchema, followSchema, authySchema
from nesplash.authy.utils import verify_authy_token
from werkzeug.security import check_password_hash
from nesplash.extensions import cache

import time

user_bp = Blueprint("user", __name__)

check = False
# signin and signup routes
@user_bp.route("/signup")
@cache.cached(timeout=60*60*24)
def signup():
    return render_template("signup.html")

@user_bp.route("/signin")
@cache.cached(timeout=60*60*24)
def signin():
    return render_template("signin.html")

@user_bp.route("/api/user", methods=['GET', 'POST', 'PATCH', 'DELETE'])
def member():
    # 註冊
    if request.method == "POST":
        username = request.json["username"]
        email = request.json["email"].lower()
        password = request.json["password"]
    
        email_check = User.query.filter_by(email=email).first()
        
        if email_check:
            return jsonify({"error": True, "message": "email has already been taken, please use another one"})

        username_check = User.query.filter_by(username=username).first()
        
        if username_check is not None:
            if username_check.username == username:
                return jsonify({"error": True, "message": "duplicate username"})

        user = User(
            username=username, 
            email=email,
            methods=Method.query.filter_by(name="normal").first()
        )
        user.set_password(password)
        send_register_mail(user)
        db.session.add(user)
        db.session.commit()
        return jsonify({"ok": True}), 201
    # 登入
    elif request.method == "PATCH":
        email = request.json["email"]
        password = request.json["password"]
        user = User.query.filter_by(email=email).first()
        if user is None:
            return jsonify({"error": True, "message": "none exist user"}), 400
        else:
            if user.validate_password(password):
                session["email"] = user.email
                if user.useAuthy == False:
                    global check
                    check = True
                    return jsonify({"ok": True, "message": user.useAuthy}), 201
                else:
                    return jsonify({"ok": True, "message": user.useAuthy}), 201
            else:
                return jsonify({"error": True, "message": "wrong password"}), 401
    # 登出
    elif request.method == "DELETE":
        session.pop("email")
        check = False 
        return jsonify({"ok": True})
    else:
        sess = session.get("email")
        if sess:
            user = User.query.filter_by(email=sess).first()
            return jsonify({"message": {
                "id": user.id,
                "email": user.email,
                "username": user.username,
                "role_id": user.role_id,
                "lock_status": user.lock_status,
                "check": check
            }})
        else:
            return jsonify({"message": None}), 403


@user_bp.route("/api/user/2fa/check/token", methods=['POST'])
@login_required
def check_2fa_token(*args, **kwargs):
    token = request.json["token"]
    if token is None:
        return jsonify({"error": "none exist token"}), 400

    user = User.query.filter_by(email=kwargs["email"]).first()
    if user == None:
        return jsonify({"error": "none exist user"}), 400

    authy = authySchema.dump(user.authys)
    verification = verify_authy_token(authy[0]["authy_id"], token)
    message = verification.ok()
    if message:
        global check
        check = True
        return jsonify({"ok": True})
    else:
        return jsonify({"error": "Token is invalid"})

# reset change routes
@user_bp.route("/api/user/reset-page", methods=['GET', 'POST'])
def reset_page():
    if request.method == "POST":
        email =request.json["email"]

        if email == "":
            return jsonify({"error": True, "message": "email must not be empty"}), 400

        user = User.query.filter_by(email=email).first()
        if user:
            send_change_password_mail(user)
            return jsonify({"ok": True})
        else:
            return jsonify({"error": "none exist user"}), 400

    return render_template("reset_request.html")

@user_bp.route("/api/user/reset-password/<token>", methods=['GET', 'POST'])
def reset_password(token):
    if request.method == "POST":
        password = request.json["password"]
        conform_password = request.json["conform_password"]

        if not password == conform_password:
            return jsonify({"error": True, "message": "password and conform_password not same"}), 400

        user = User.validate_token(token)
        
        if user is None:
            return jsonify({"error": True, "message": "Invalid or expired token"}), 400
        else:
            user.set_password(password)
            db.session.commit()
            return jsonify({"ok": True})
        
    return render_template("reset_password.html")

@user_bp.route("/api/user/change-password", methods=['POST'])
@login_required
def change_password(*args, **kwargs):
    user = User.query.filter_by(email=kwargs['email']).first()

    if user is None:
        return jsonify({"error": "none exist user"}), 400

    if request.method == "POST":
        password = request.json["password"]
        conform_password = request.json["conform_password"]

        if not password == conform_password:
            return jsonify({"error": True, "message": "password and conform_password not same"}), 400
        
        user.set_password(password)
        db.session.commit()
        return jsonify({"ok": True})


# confirm routes
@user_bp.route("/api/user/confirm/<token>")
def confirm_email(token):
    return render_template("account/confirm.html")

@user_bp.route("/api/user/confirm-email", methods=['POST'])
def confirm_signUpToken():
    if request.method == 'POST':
        token = request.json["token"]

        user = User.validate_token(token)

        if user is None:
            return jsonify({"error": True, "message": "Invalid or expired token"}), 400

        user.confirmed = 1
        db.session.commit()

        return jsonify({"ok": True, "message": user.username})


# public routess
@user_bp.route("/public/<int:id>")
def public_page(id):
    return render_template("public.html")

@user_bp.route("/api/public/<int:user_id>")
def public_page_api(user_id):
    page = request.args.get("page", None)
    user = User.query.get_or_404(user_id)
    photos = Photo.query.filter_by(author_id=user_id).order_by(Photo.id.asc()).offset(int(page)*12).limit(12)
    
    results = photoSchema.dump(photos)
    
    data = {
        "username": user.username,
        "link": user.link,
        "bio": user.bio,
        "location": user.location,
        "profile_image": user.profile_image,
        "total_collections": user.total_collections,
        "total_photos": user.total_photos
    }

    if results != []:
        if len(results) < 12:
            return jsonify({"nextPage": None, "message": results, "user": data})
        else:
            query_data_check = Photo.query.filter_by(author_id=user_id).order_by(Photo.id.asc()).offset(int(page)*12).limit(12)
            results_check = photoSchema.dump(query_data_check)
            if results_check != []:
                return jsonify({"nextPage": int(page) + 1, "message": results, "user": data})
            else:
                return jsonify({"NextPage": None, "message": results, "user": data})
    else:
        if data == []:
            return jsonify({"nextPage": None, "message": []})
        return jsonify({"nextPage": None, "user": data})


# account person and pictures routes
@user_bp.route("/account/upload_pictures")
@login_required
def upload_pictures_page(*args, **kwargs):
    return render_template("account/upload_pictures_page.html")

@user_bp.route("/account/data")
@login_required
def person_data(*args, **kwargs):
    return render_template("account/profile.html")

@user_bp.route("/api/account/data")
@login_required
def person_data_api(*args, **kwargs):
    sess = kwargs["email"]
    if sess:
        current_user = User.query.filter_by(email=sess).first()
        return jsonify({"message": {
            "id": current_user.id,
            "email": current_user.email,
            "username": current_user.username,
            "location": current_user.location,
            "link": current_user.link,
            "bio": current_user.bio,
            "profile_image": current_user.profile_image,
            "useAuthy": current_user.useAuthy,
            "confirmed_status": current_user.confirmed,
            "lock_status": current_user.lock_status,
            "Method": {
                "user_method": current_user.methods.name
            }
        }})
    else:
        jsonify({"message": []})


@user_bp.route("/api/user/change-bio", methods=['POST'])
@login_required
def change_bio(*args, **kwargs):
    user = User.query.filter_by(email=kwargs['email']).first()
    if user is None:
        return jsonify({"error": "none exist user"}), 400

    if request.method == "POST":
        bio = request.json["bio"]
        user.bio = bio
        db.session.commit()
        return jsonify({"ok": True})

@user_bp.route("/api/user/change-username", methods=['POST'])
@login_required
def change_username(*args, **kwargs):
    user = User.query.filter_by(email=kwargs['email']).first()
    if user is None:
        return jsonify({"error": "none exist user"}), 400

    if request.method == "POST":
        username = request.json["username"]

nesplash/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
    integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    {% block style %}{% endblock %}
    <title>Nesplash_O</title>
</head>
<body>
    <header class="main-header">
        <nav class="nav">
            <div class="nav-div-bars">
                <i class="fas fa-bars"></i>
            </div>
            <div class="nav-div-left">
                <li><a class="website-title navbar-brand-2" href="{{ url_for('main.index') }}">Nesplash_O</a></li> 
                <li><a class="navbar-brand-2" href="{{ url_for('foodie.index') }}">Foodie</a></li>
                <li><a class="navbar-brand-2" href="{{ url_for('nature.index') }}">Nature</a></li>
                <li><a class="navbar-brand-2" href="{{ url_for('architecture.index') }}">Architecture</a></li>
                <li><a class="navbar-brand-2" href="{{ url_for('travel.index') }}">Travel</a></li>
                <li><a class="navbar-brand-2" href="{{ url_for('athletics.index') }}">Athletics</a></li>
                <li><a class="navbar-brand-2" href="{{ url_for('people.index') }}">People</a></li>
            </div>
            <div class="nav-div-right">
                <li class="nav-li-right">
                    <a id="signin" class="navbar-brand-2" href="{{ url_for('user.signin') }}">Signin</a>
                    <a id="signup" class="navbar-brand-2" href="{{ url_for('user.signup') }}">Signup</a>
                </li>
            </div>
            <div class="bars-div">
                <div class="bars-triangle"></div>
                <div class="nav-div-barsBlock">
                    <li><a class="website-title navbar-brand-3" href="{{ url_for('main.index') }}">Nesplash_O</a></li>
                    <li><a class="navbar-brand-3" href="{{ url_for('foodie.index') }}">Foodie</a></li>
                    <li><a class="navbar-brand-3" href="{{ url_for('nature.index') }}">Nature</a></li>
                    <li><a class="navbar-brand-3" href="{{ url_for('architecture.index') }}">Architecture</a></li>
                    <li><a class="navbar-brand-3" href="{{ url_for('travel.index') }}">Travel</a></li>
                    <li><a class="navbar-brand-3" href="{{ url_for('athletics.index') }}">Athletics</a></li>
                    <li><a class="navbar-brand-3" href="{{ url_for('people.index') }}">People</a></li>
                </div>
            </div>
        </nav>
    </header>

    <section class="main-section">
        {% block content %}{% endblock %}
    </section>
    <script>
        window.port = "http://127.0.0.1:5000"
    </script>
    <script src="{{ url_for('static', filename='js/common.js') }}"></script>
    {% block script %}{% endblock %}
</body>
</html>

nesplash/templates/main.html
{% extends 'layout.html' %}


{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}

{% block content %}
    <div class="main-section-1-div">
        <div>
            <form class="section-1-searchBox">
                <input type="text" placeholder="輸入關鍵字" id="section-1-input-keyword" minlength="3">
                <div class="section-1-searchDiv">
                    <button id="mag-btn">
                        <img src="{{ url_for('static', filename='icon_search.png') }}" id="section-1-mag" />
                    </button>
                </div>
            </form>
        </div>
        <div class="search-keyword-select" style="display: flex;">
            <div id="search-photos" style="background: rgb(68, 136, 153);" class="search-keyword"></div>
            <label>photos</label>
            <div id="search-users" style="background: white;" class="search-keyword"></div>
            <label>users</label>
        </div>
    </div>
    
    <section id="main-section-2">
        <!-- dynamic loading photo's data -->
    </section>
{% endblock %}

{% block script %}
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

nesplash/templates/public.html
{% extends 'layout.html' %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/public.css') }}">
{% endblock %}

{% block content %}
    <div class="public-section-1">
        <!-- dynamic loading user's data -->
    </div>
    <hr>
    <div id="public-section-2">
        <!-- dynamic loading photo's data -->
    </div>
{% endblock %}


{% block script %}
    <script src="{{ url_for('static', filename='js/public.js') }}"></script>
{% endblock %}

nesplash/templates/reset_password.html
{% extends 'layout.html' %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/reset.css') }}">
{% endblock %}

{% block content %}
    <form class="resetRequest-form" onsubmit="return false">
        <div class="resetRequest-div">
            <label class="resetRequest-label">Password : </label>
            <input class="resetRequest-password" placeholder="輸入密碼" type="password" required>
        </div>
        <div class="resetRequest-div">
            <label class="resetRequest-label">Confirm Passowrd : </label>
            <input class="resetRequest-confirm-password" placeholder="請再輸入一次密碼" type="password" required>
        </div>
        <div class="resetRequest-div">
            <button class="resetRequest-btn">Submit</button>
    </form>
{% endblock %}


{% block script %}
    <script src="{{ url_for('static', filename='js/token.js') }}"></script>
{% endblock %}

nesplash/templates/reset_request.html
{% extends 'layout.html' %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/reset.css') }}">
{% endblock %}

{% block content %}
    <form class="resetRequest-form" onsubmit="return false">
        <div class="resetRequest-div">
            <label class="resetRequest-label">Email : </label>
            <input class="resetRequest-email" placeholder="輸入電子信箱" type="email" required>
        </div>
        <div class="resetRequest-div">
        <button class="resetRequest-btn">Submit</button>
    </form>
{% endblock %}


{% block script %}
    <script src="{{ url_for('static', filename='js/reset.js') }}"></script>
{% endblock %}

nesplash/templates/signin.html
{% extends 'layout.html' %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/signin.css') }}" >
{% endblock %}

{% block content %}
    <form class="signin-form" onsubmit="return false">
        <div class="signin-iconDiv">
            <legend class="signin-title">Log in</legend>
            <div>
                <a href="{{ url_for('auth.oauth_login', provider_name='google') }}"><i class="fab fa-google"></i></a>
                <a href="{{ url_for('auth.oauth_login', provider_name='github') }}"><i class="fab fa-github"></i></a>
            </div>
        </div>
        <hr>
        <div class="signin-div">
            <label class="signin-label">Email : </label>
            <input class="signin-email" placeholder="輸入電子信箱" type="email" required>
        </div>
        <div class="signin-div">
            <label class="signin-label">Password : </label>
            <input class="signin-password" placeholder="輸入密碼" type="password" required>
        </div>
        <button class="signin-btn">signin</button>
        <span class="signin-span">Don't have an account?<a class="signin-a"href="{{ url_for('user.signup') }}">Join</a></span>
        <div class="signin-forgotDiv">
            <a class="signin-forgot" href="{{ url_for('user.reset_page') }}">Forgot Passowrd?</a>
        </div>
    </form>
{% endblock %}


{% block script %}
    <script src="{{ url_for('static', filename='js/signin.js') }}"></script>
{% endblock %}

nesplash/templates/signup.html
{% extends 'layout.html' %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/signup.css') }}">
{% endblock %}

{% block content %}
    <form class="signup-form" onsubmit="return false">
        <legend class="signup-title">Register</legend>
        <hr>
        <div class="signup-div">
            <label class="signup-label">Username : </label>
            <input class="signup-username" placeholder="輸入姓名" type="email" minlength="3" maxlength="30" required>
        </div>
        <div class="signup-div">
            <label class="signup-label">Email : </label>
            <input class="signup-email" placeholder="輸入電子信箱" type="email" required>
        </div>
        <div class="signup-div">
            <label class="signup-label">Password : </label>
            <input class="signup-password" placeholder="輸入密碼" type="password" required>
        </div>
        <button class="signup-btn">signup</button>
        <span class="signup-span">Already have an account?<a class="signup-a" href="{{ url_for('user.signin') }}">Login</a></span>
        <div style="position: relative; top: 35px;"></div>
    </form>
{% endblock %}


{% block script %}
    <script src="{{ url_for('static', filename='js/signup.js') }}"></script>
{% endblock %}